using System;
using System.IO;
using System.Reflection;
using LibreLancer.Graphics;

namespace LibreLancer.Render;

/// <summary>
/// SMAA lookup textures (graphics roadmap 4.7, "phase 1.5"). The reference
/// AreaTex (160x560 RG8) and SearchTex (64x16 R8) byte payloads from
/// https://github.com/iryoku/smaa ship as embedded resources (generated by
/// scripts/smaa_textures.py, license in Shaders/SMAA/LICENSE-SMAA.txt) and
/// upload once per process, IblResources-style.
/// AreaTex expands to BGRA8 on the CPU: neither backend exposes an unsigned
/// RG8 SurfaceFormat (GL maps NormalizedByte2 to signed RG8I, Vulkan has no
/// mapping at all) - the shader only reads .rg, so the wasted channels are
/// 175KB of irrelevance.
/// </summary>
public static class SmaaTextures
{
    public const int AreaWidth = 160;
    public const int AreaHeight = 560;
    public const int SearchWidth = 64;
    public const int SearchHeight = 16;

    private static Texture2D? areaTex;
    private static Texture2D? searchTex;

    public static Texture2D GetAreaTex(RenderContext rstate)
    {
        if (areaTex != null && !areaTex.IsDisposed)
        {
            return areaTex;
        }

        var rg = ReadResource("SMAA.AreaTex.bin", AreaWidth * AreaHeight * 2);
        var bgra = new byte[AreaWidth * AreaHeight * 4];
        for (var i = 0; i < AreaWidth * AreaHeight; i++)
        {
            bgra[(i * 4) + 2] = rg[i * 2];       // R <- area.r
            bgra[(i * 4) + 1] = rg[(i * 2) + 1]; // G <- area.g
            bgra[(i * 4) + 3] = 255;
        }

        areaTex = new Texture2D(rstate, AreaWidth, AreaHeight, false, SurfaceFormat.Bgra8);
        areaTex.SetData(bgra);
        FLLog.Info("Render", "SMAA AreaTex uploaded (160x560)");
        return areaTex;
    }

    public static Texture2D GetSearchTex(RenderContext rstate)
    {
        if (searchTex != null && !searchTex.IsDisposed)
        {
            return searchTex;
        }

        var bytes = ReadResource("SMAA.SearchTex.bin", SearchWidth * SearchHeight);
        searchTex = new Texture2D(rstate, SearchWidth, SearchHeight, false, SurfaceFormat.R8);
        searchTex.SetData(bytes);
        FLLog.Info("Render", "SMAA SearchTex uploaded (64x16)");
        return searchTex;
    }

    private static byte[] ReadResource(string name, int expectedLength)
    {
        using var stream = typeof(SmaaTextures).Assembly.GetManifestResourceStream(name)
                           ?? throw new InvalidOperationException($"Missing embedded resource {name}");
        var data = new byte[expectedLength];
        var read = stream.Read(data, 0, expectedLength);
        if (read != expectedLength || stream.ReadByte() != -1)
        {
            throw new InvalidDataException(
                $"Embedded resource {name}: expected exactly {expectedLength} bytes");
        }
        return data;
    }
}
